### ISSUE TITLE
Migrate to buildSrc and composite builds

### ISSUE THREAD

**Issue by wax911** [AniTrend/anitrend-v2#59]
# AniTrend Issue Guidelines

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/AniTrend/anitrend-v2/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**You may find an answer in already closed issues**: [Issues Closed](https://github.com/AniTrend/anitrend-v2/issues?q=is%3Aissue+is%3Aclosed)

## Planing Information

Managing multiple module dependencies and configuration through buildSrc rather than using gradle script files, as well as excluding sub-modules

**Comment by raniesantos** [comment]
ganbatte
